# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Zoinks, it's Kunesh
email: jdkunesh@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The personal site of Jason Daniel Kunesh. Sometime mustachio'd Chicagoan. Hiya!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jdkunesh.com" # the base hostname & protocol for your site
twitter_username: jdkunesh
github_username:  jdkunesh

# Build settings
markdown: kramdown
